# Generated by Django 5.0.1 on 2024-04-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('basic_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pay_slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_absent', models.IntegerField(default=0)),
                ('loan_iou', models.IntegerField(default=0)),
                ('deductions', models.IntegerField(default=500)),
                ('bonus', models.IntegerField(default=0)),
                ('monthly_earning', models.IntegerField(default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staff')),
            ],
        ),
    ]
